import { useEffect, useState } from 'react';
import { ArrowRight, CheckCircle2, ChevronDown, Clock3, MapPin, Menu, Phone, Send, ShieldCheck, Star, X, MessageCircle, ChevronUp } from 'lucide-react';
import { NavLink, Link, useLocation } from 'react-router-dom';
import { business, contactLinks, serviceAreas } from './data/business';
import { faqs } from './data/content';

export const CallButton = ({ children = 'Call Now', className = 'button button-primary' }) => <a className={className} href={contactLinks.phone}><Phone size={18}/>{children}</a>;
export const WhatsAppButton = ({ children = 'WhatsApp Us', className = 'button button-light' }) => <a className={className} href={contactLinks.whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={18}/>{children}</a>;

export function EmergencyBar() { return <div className="emergency-bar"><div className="shell emergency-inner"><span><span className="pulse-dot"/> Need a Plumber? We're Ready to Help!</span><div><CallButton className="text-link">Call Now <ArrowRight size={15}/></CallButton><Link className="text-link" to="/emergency-plumbing">Emergency Plumbing</Link></div></div></div> }
export function Logo() { return <Link className="logo" to="/"><span className="logo-mark"><WrenchIcon /></span><span>Nagaraju <em>Plumbing Services</em></span></Link> }
function WrenchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 5.5a6 6 0 0 1-7.7 5.7L6.1 18.4a2.1 2.1 0 1 1-3-3l7.2-7.2A6 6 0 0 1 18.7 2l-3.3 3.3 2 2L21 5.5Z" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function Navbar(){ const [open,setOpen]=useState(false); const loc=useLocation(); useEffect(()=>setOpen(false),[loc]); const links=[['/','Home'],['/services','Services'],['/about','About'],['/emergency-plumbing','Emergency'],['/contact','Contact']]; return <header className="site-header"><div className="shell nav"><Logo/><nav className={open?'nav-links open':'nav-links'} aria-label="Main navigation">{links.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}<CallButton className="button button-primary nav-call">Call Now</CallButton></nav><button className="menu-button" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><CallButton className="mobile-call">Call</CallButton></div></header>}

export function Footer(){return <footer><div className="shell footer-grid"><div><Logo/><p>Reliable plumbing solutions for homes and businesses.</p><div className="footer-cta"><CallButton>Call Now</CallButton></div></div><div><h3>Quick Links</h3><Link to="/">Home</Link><Link to="/services">Services</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/emergency-plumbing">Emergency Plumbing</Link></div><div><h3>Services</h3><Link to="/services/emergency-plumbing">Emergency Plumbing</Link><Link to="/services/pipe-repair">Pipe Repair</Link><Link to="/services/water-leak-repair">Leak Repair</Link><Link to="/services/drain-cleaning">Drain Cleaning</Link><Link to="/services/bathroom-plumbing">Bathroom Plumbing</Link><Link to="/services/kitchen-plumbing">Kitchen Plumbing</Link></div><div><h3>Contact</h3><a href={contactLinks.phone}>Phone: {business.phone}</a><a href={contactLinks.whatsapp} target="_blank" rel="noreferrer">WhatsApp: {business.whatsapp}</a><a href={`mailto:${business.email}`}>Email: {business.email}</a><span>Address: {business.address}</span><h3 className="hours-heading">Business Hours</h3><span>{business.hours}</span></div></div><div className="shell copyright">© 2026 {business.name}. All rights reserved.</div></footer>}
export function SectionHeading({ eyebrow, title, text, center=true }){return <div className={center?'section-heading centered':'section-heading'}>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>}
export function PageHero({ eyebrow, title, text, emergency=false, children }) {return <section className={emergency?'page-hero emergency-page-hero':'page-hero'}><div className="shell"><div className="hero-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p>{children}</div></div></section>}
export function CTASection({ emergency=false, title='Need a Plumber? We’re Just a Call Away.', text='Get professional plumbing assistance when you need it.' }) {return <section className={emergency?'cta emergency-cta':'cta'}><div className="shell cta-inner"><div><span className="eyebrow">{emergency?'URGENT PLUMBING HELP':'READY WHEN YOU NEED US'}</span><h2>{title}</h2><p>{text}</p></div><div className="button-row"><CallButton>{emergency?'Call for Emergency Service':'Call Now'}</CallButton><Link className="button button-outline-light" to="/contact">{emergency?'Contact Us':'Request a Service'}</Link></div></div></section>}
export function FAQSection({ limit }) { const list=limit?faqs.slice(0,limit):faqs; const [active,setActive]=useState(0); return <section className="section faq-section"><div className="shell narrow"><SectionHeading eyebrow="HELPFUL ANSWERS" title="Frequently Asked Questions" text="Clear answers to common service questions."/>{list.map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={active===i} onClick={()=>setActive(active===i?-1:i)}><span>{q}</span><ChevronDown className={active===i?'rotate':''}/></button>{active===i&&<p>{a}</p>}</div>)}</div></section>}
export function ServiceAreas(){return <section className="section areas"><div className="shell areas-inner"><div><span className="eyebrow">LOCAL SERVICE</span><h2>Areas We Serve</h2><p>We serve the areas listed here. Replace these editable locations with the business’s confirmed service areas.</p><Link to="/contact" className="inline-link">Check availability in your area <ArrowRight size={17}/></Link></div><div className="area-list">{serviceAreas.map((x,i)=><div key={x}><span>0{i+1}</span><MapPin size={19}/>{x}</div>)}</div></div></section>}
export function ContactForm(){const [form,setForm]=useState({});const [errors,setErrors]=useState({});const [status,setStatus]=useState('');const fields=[['name','Full Name','text'],['phone','Phone Number','tel'],['email','Email','email'],['service','Service Required','select'],['date','Preferred Date','date'],['time','Preferred Time','time'],['address','Address','text']]; function submit(e){e.preventDefault();const next={};['name','phone','service','address'].forEach(k=>{if(!form[k]) next[k]='This field is required.'}); if(form.email&&!/^\S+@\S+\.\S+$/.test(form.email))next.email='Enter a valid email address.';setErrors(next);if(!Object.keys(next).length){setStatus('success');}}return <form className="contact-form" noValidate onSubmit={submit}>{fields.map(([key,label,type])=><label key={key}>{label}{type==='select'?<select value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Select a service</option>{['Emergency Plumbing','Pipe Repair','Water Leak Repair','Drain Cleaning','Bathroom Plumbing','Kitchen Plumbing','Water Tank Services','New Plumbing Installation','Other'].map(x=><option key={x}>{x}</option>)}</select>:<input type={type} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>} {errors[key]&&<small className="error">{errors[key]}</small>}</label>)}<label>Message<textarea rows="4" value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Tell us briefly about the plumbing issue"/></label>{status==='success'?<div className="form-success"><CheckCircle2/> Your request is ready to send. Connect this form to your email or API service before launch.</div>:<button className="button button-primary submit" type="submit"><Send size={18}/>Submit Service Request</button>}<p className="form-note">This form is frontend-ready. Connect it to a backend or email service before launch.</p></form>}
export function FloatingActions(){const [show,setShow]=useState(false);useEffect(()=>{const f=()=>setShow(scrollY>500);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <><a className="float-whatsapp" href={contactLinks.whatsapp} target="_blank" rel="noreferrer" aria-label="Contact us on WhatsApp"><MessageCircle/></a>{show&&<button className="to-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top"><ChevronUp/></button>}<div className="mobile-bottom"><CallButton>Call Now</CallButton><WhatsAppButton>WhatsApp</WhatsAppButton></div></>}
